base:
  seed: 42
  write_iter_num : 10
  coco_path : ../Dataset
  train_args :
    num_epochs : 1
    network_depth : 18
    num_classes : 80
    batch_size : 8
    lr : 0.001
    weight_decay : 0.01
